### ISSUE TITLE
Option to filter RSS feed

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#1]
Add filters to RSS feed, so user can get feed of only actions performed by a specific user, for attachments, for posts, etc.

**Comment by viktorbijlenga** [comment]
Is this making it's way into the plugin? It's would be a nice feature. It would also be great if the rss feed showed which user who signed in, instead of only displaying the action "Logged in".

**Comment by bonny** [comment]
Still on it's way in. Very slowly. Not sure when or how it will appear.

**Comment by viktorbijlenga** [comment]
Sounds great! Big fan of simple history.

**Comment by bonny** [comment]
Closing this, I will work on a solution where selected filter in the GUI can be used for a RSS-feed or for notifications, etc. That will be more user friendly.
