### ISSUE TITLE
Undefined index: _user_id, WP_DEBUG true and no user

### ISSUE THREAD

**Issue by Ciantic** [bonny/WordPress-Simple-History#100]
I get this, and the UI goes broken:

*Notice*:  Undefined index: _user_id in *../simple-history/loggers/SimpleUserLogger.php* on line *315*

I have WP_DEBUG true and events with no user id associated with them.

UI works if I disable WP_DEBUG, but it should work with it enabled also.

**Comment by bonny** [comment]
So you have logged events about people editing their profiles, but with no user id logged? It sounds wierd indeed..

**Comment by Ciantic** [comment]
@bonny if anything updates a post, e.g. cron job, it will not have a user. The UI itself understands the non existing user, it says "Other". Something in PHP is not.

**Comment by bonny** [comment]
thanks for the clearification. any chance by the way that you could post the data you see when you click the time of the event? there is a popup with lots of info, and i'm curios about the data there...

**Comment by bonny** [comment]
This is fixed in version 2.5.1.
