### ISSUE TITLE
Dashboard JS errors

### ISSUE THREAD

**Issue by guillaumemolter** [bonny/WordPress-Simple-History#101]
Hi,

I'm getting multiple JS errors on the Dashboard widget:
<img width="1279" alt="screen shot 2015-12-22 at 11 50 21" src="https://cloud.githubusercontent.com/assets/1478527/11960769/3c5b4fc8-a8a2-11e5-9b72-a7e618eca5ec.png">

Errors are disappearing as soon as I deactivate the Dashboard widget.

The first error seems to point out in the thickbox direction as it refers to this line:

`if(!params['modal']){jQuery(document).bind('keydown.thickbox',function(e){if(e.which==27){tb_remove();return false;}});}}catch(e){}}`

Using latest version of WordPress, all plugins are up to date.

**Comment by bonny** [comment]
I don't manage to reproduce this. Any chance you could test with a fresh install, with no custom theme and no installed plugins?

**Comment by bonny** [comment]
The latest version contains a possible fix for this. Please test latest version and if issue still exists please let me know.
