### ISSUE TITLE
Logs from custom logger not showing up

### ISSUE THREAD

**Issue by Inggo-inHomePortal** [bonny/WordPress-Simple-History#103]
Hi. I created a custom logger with a namespace. The items are being logged (I checked the DB) but is not showing up in the WP dashboard.

**Comment by bonny** [comment]
Difficult to say. Any change I could take a look at your logger and try it?

**Comment by Inggo-inHomePortal** [comment]
Here's a gist of the class I created:

https://gist.github.com/Inggo-inHomePortal/7920d6791de16878cf91

I can see them stored at the database, but are not appearing in the wp-admin dashboard or the Simple History page. We are using a multisite installation, by the way.

**Comment by bonny** [comment]
This is fixed in the next version of the plugin.
