### ISSUE TITLE
Error in your SQL syntax

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#108]
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use
near `'amdbta_simple_history' WHERE DATE_ADD(date, INTERVAL 60 DAY) < now()` at line 1
in query `SELECT id FROM 'amdbta_simple_history' WHERE DATE_ADD(date, INTERVAL 60 DAY) < now()` kÃ©szÃ­tette do_action_ref_array, call_user_func_array, SimpleHistory->maybe_purge_db, `SimpleHistory->purge_db`

**Comment by szepeviktor** [comment]
What more should I tell you?

**Comment by bonny** [comment]
thanks for the report!

**Comment by szepeviktor** [comment]
Thanks.

**Comment by szepeviktor** [comment]
:ship:
