### ISSUE TITLE
chinese char,export to csv Could not recognize

### ISSUE THREAD

**Issue by zhuroufanzi** [bonny/WordPress-Simple-History#109]
hi man，i use the plugin to keep admin log. It's must the best plugin whatever i saw !
but,when the post title&content insert chinese char, i export log to csv ,then opened the csv by office2007.
all chinese char Could not recognize. what shall i do?

the right show is :发发发发发反反复复
​but it wrong.like：瀵嗗瘑楹婚夯濡堝濡堝浠?

by the way,Simple History 2.5.3,download from here. my wp version is 4.5beta 2

**Comment by bonny** [comment]
I tried this and the csv-export works fine when importing to for example Google Drive or when using quicklook in os x. I don't have Excel so can't try that. It looks like an encoding error, so try importing the file using another charset.

![history-chinese-chars](https://cloud.githubusercontent.com/assets/221570/13883368/5b47c95e-ed29-11e5-9813-61067b75e87e.png)

**Comment by zhuroufanzi** [comment]
hum  hum,you are right. I use other soft to open the csv, I got it !  But i don't know why.

maybe...
