### ISSUE TITLE
Updating a plugin via WP-CLI results in an untransformed context placeholder

### ISSUE THREAD

**Issue by johnbillion** [bonny/WordPress-Simple-History#113]
Scenario: An update for a plugin is available, so I run the following WP-CLI command:

`wp plugin update <plugin>`

This results in an entry in Simple History that's missing information for its previous version (in the `plugin_prev_version` placeholder):

<img width="539" alt="screen shot 2016-05-15 at 23 10 05" src="https://cloud.githubusercontent.com/assets/208434/15277117/32f7e9ce-1af2-11e6-9f91-db7b8369029b.png">

**Comment by bonny** [comment]
The just released version 2.9 should fix this. "It worked for me" anyway then I tested it... :)
