### ISSUE TITLE
Exporting Results (Feature Request)

### ISSUE THREAD

**Issue by briwilcox** [bonny/WordPress-Simple-History#116]
Assuming it isn't currently possible it would be nice to export the data this plugin displays as a csv or excel file. 

Scenario would be sharing this information with team members or managers who don't have WordPress access.

**Comment by bonny** [comment]
There is an export function already in "Settings -> Simple History -> Export". It might be difficult to find however :) Is that what you need?

**Comment by briwilcox** [comment]
Yup! That did the trick. 

If it's a common use case I might add a link to that in the simple history right hand column either over or under the support box, otherwise no worries. Thanks for making a great plugin.
