### ISSUE TITLE
Log AdminColums changes

### ISSUE THREAD

**Issue by 68B** [bonny/WordPress-Simple-History#117]
Hi,

I'm using Admin Columns	(https://nl.wordpress.org/plugins/codepress-admin-columns/) but the changes are not logged into Simple History. Can you modify the script to hook into all changes?

Thanks,
Robert

**Comment by bonny** [comment]
That may be possible. What kind of actions would you like to see logged?

**Comment by 68B** [comment]
With the Admin Columns you have the inline edit function, but the changes to make to the fields are not logged now;
https://www.admincolumns.com/inline-edit-columns/

**Comment by twaiiiin** [comment]
That's true. I'm editing fields (from Advanced Custom Fied) with the inline edit function from Admin Columns Pro and the changes are not logged.

You could also add a log when someone add/remove/change columns or column sets with the plugin.

**Comment by bonny** [comment]
I don't use the plugin myself and it costs money so not much I can do. You could try to contact the plugin author and see if they can add support for Simple History in their plugin.
