### ISSUE TITLE
Too many queries caused system run out of resources

### ISSUE THREAD

**Issue by AkatsukiRyuunosuke** [bonny/WordPress-Simple-History#118]
Days ago, I tried to stress test my WordPress site using wpscan.
I tried the "brute force password attacks" to my site and ran for half a day, about 3 million failed login attempts were logged.

Then comes to the problem, When I opened the Dashboard of my WordPress, the simple history was loading the failed attempts for too long time, then my server stopped showing pages, and it crashed.
The php and mysql used a ton of resource and blew the server out of my roof.

Hope you can limit the query when the simple history load the info.

**Comment by bonny** [comment]
Thanks for the issue. The problem with brute force attempts and large log files is something I'm aware of and a solution is being worked on.
