### ISSUE TITLE
French translation problem

### ISSUE THREAD

**Issue by etlel** [bonny/WordPress-Simple-History#120]
Some ugly symbols are displayed to the user because of the spaces in simple-history-fr_FR.po, line 315:

`msgstr "% 1 $ d événements aujourd'hui d'un utilisateur."`

**Comment by ajoah** [comment]
Hi @etlel,

This issue has been fixed, no ?

**Comment by bonny** [comment]
I never quite understand how the translations work, but if I check
https://translate.wordpress.org/projects/wp-plugins/simple-history/dev/fr/default/?filters%5Bterm%5D=%251%24d+events+today+from+one+user&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
it seems to be fixed there.
