### ISSUE TITLE
tries to show pdf preview (which won't work)

### ISSUE THREAD

**Issue by nicmare** [bonny/WordPress-Simple-History#124]
i just noticed a minor "bug", where simply history obviously tries to preview a pdf file:
![screenshot 2017-02-09 17 41 06](https://cloud.githubusercontent.com/assets/898582/22793099/23572aa8-eeef-11e6-8347-122e0a578be8.png)
the image it tries to load is "https://molitor-berlin.de/wp-content/uploads/2017/02/Invoice-2017027.jpeg". I don't know where this filepath comes from. Because there is no file like that. We only have WooCommerce with invoice-plugin. So i assume simply history somehow tries to build a preview for that?!

**Comment by bonny** [comment]
I can't reproduce this so maybe I did fix it sometime in the last two years :)
