### ISSUE TITLE
The plugin stucks in loading

### ISSUE THREAD

**Issue by 1geeky** [bonny/WordPress-Simple-History#125]
Hi,
It seems the support forum on the WordPress site is inactive, so I repost my issue here:
I’ve used this great plugin for a while now but recently it doesn’t work correctly as a page under the dashboard menu and doesn’t load. It sounds that the js file of the chart is the culprit. However the plugin loads as a widget in the Dashboard’s main page.

This is the log, in console:

```
Chart.js:2632 Uncaught SyntaxError: Unexpected end of input
index.php:861 Uncaught ReferenceError: Simple_History_Chart is not defined
    at HTMLDocument.<anonymous> (index.php:861)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at Function.ready (load-scripts.php:2)
    at HTMLDocument.K (load-scripts.php:2)
(anonymous) @ index.php:861
i @ load-scripts.php:2
fireWith @ load-scripts.php:2
ready @ load-scripts.php:2
K @ load-scripts.php:2
```

The `chart.js` stops here on the `line` variable:
 
```
    .
    .
    scaleZero: scaleBase
};
line.pivot();
```

**Comment by bonny** [comment]
I do answer the forums, but maybe not as often as I would like to. So let's continue using the thread over there at https://wordpress.org/support/topic/the-plugin-stucks-in-loading/.
