### ISSUE TITLE
Loggers instantiation & load_logger filter

### ISSUE THREAD

**Issue by nlemoine** [bonny/WordPress-Simple-History#129]
Hi,

I don't know if this is considered a bug. I'll explain the issue I encountered and you'll let me know. 

I used your great plugin for tracking custom stuff. So I didn't need existing loggers at all. 
For this, I went with: 
```php
add_filter('simple_history/logger/load_logger', '__return_false');
```
I loaded my custom logger: 
```php
add_action('simple_history/add_custom_logger', function($simple_history) {
    $simple_history->register_logger('My\Class\Logger');
});
```
Logging works fine. But displaying the logs throws a notice: "Undefined index SimpleLogger" here: https://github.com/bonny/WordPress-Simple-History/blob/master/inc/SimpleHistory.php#L2561

I fixed the issue with:
```php
add_filter('simple_history/logger/load_logger', function($load, $logger_basename) {
    return $logger_basename === 'SimpleLogger';
}, 10, 2);
```

But shouldn't you make sure, like you did [here](https://github.com/bonny/WordPress-Simple-History/blob/master/inc/SimpleHistory.php#L985-L987), that the base SimpleLogger is always instantiated (because SimpleLogger isn't actually a logger)?

**Comment by bonny** [comment]
Sounds a bug indeed, will be fixed in next version.
