### ISSUE TITLE
AvailableUpdatesLogger Misbehaves with MU-Plugins

### ISSUE THREAD

**Issue by vpillinger** [bonny/WordPress-Simple-History#139]
Available updates logger throws the following stack trace when using MU-Plugins like those in the bedrock framework. Turning off the Available Updates Logger resolved the issues.

![image](https://user-images.githubusercontent.com/6379913/37623965-ebd04358-2b9c-11e8-8577-2f5604f0b929.png)

**Comment by bonny** [comment]
This should be fixed now – I did not get any errors using Bedrock and MU-plugins.
