### ISSUE TITLE
Feature request: log translation updates

### ISSUE THREAD

**Issue by claudiobrandt** [bonny/WordPress-Simple-History#147]
I noticed that, though the Dashboard home recorded that I had updated a translation for a plugin, Simple History didn't log it.  Since btw I'm doing the translation of SH, I noticed that I couldn't find any original string with the word translation in it. So it appears to be intentional that translation updates are not logged. Knowing that translation updates occurred may be important sometimes. For example, a translation error may result in a variable being unintentionally mixed up with literal text, resulting in crazy stuff on the screen. Knowing that a translation was updated may help find this kind of error. Thanks.

**Comment by bonny** [comment]
Check the just released version 2.26, it has translation logging.
