### ISSUE TITLE
CSV Export API for External Requests

### ISSUE THREAD

**Issue by VR51** [bonny/WordPress-Simple-History#154]
Is there a way to access the history log in CSV format using a URL, something similar to the RSS feed link?

I'm about to write a report builder / emailer for use in remote hosts. I can get the history data from the RSS feed but I'd prefer a clean CSV version of the data.

The ability to select log type and date range will be helpful too.

**Comment by bonny** [comment]
At the moment this functionality does not exist.

**Comment by VR51** [comment]
Thanks @bonny.

I'm thinking a solution might be to create a virtual page with a tokenized URL. This page could use a specialised search template that answers queries about the Simple History logs. This would then give us a REST endpoint (I think. Not sure about virtual pages). What do you think?

**Comment by bonny** [comment]
I believe WP CLI can be used to achieve this.
