### ISSUE TITLE
Upload Portuguese (Portugal) translation

### ISSUE THREAD

**Issue by pedlima** [bonny/WordPress-Simple-History#157]
Hi,

I have converted Brasilian translation file into Portuguese from Portugal, which has some differences.

If you want, please use it:

[simple-history-pt_PT.zip](https://github.com/bonny/WordPress-Simple-History/files/2721406/simple-history-pt_PT.zip)

Best regards,
Pedro

**Comment by bonny** [comment]
Thanks Pedro! That's great that to hear that you have translated the plugin to Portuguese.

The tranlation of the plugin takes place over at
https://translate.wordpress.org/locale/pt/default/wp-plugins/simple-history.

Any change you could add or import your translations there?

**Comment by pedlima** [comment]
Hi Pär,

 

Yes, attached there’s the complete translation.

 

Is there a way to send these translations to WP translations?

 

I mean, having to put this manually takes time, and I don’t have the time right now unfortunately. :(

 

Best regards,

Pedro Lima

 

 



 

Av. da República, 6, 7º Dir. - 1050-191 Lisboa

 

Helpdesk

w_ suporte.maidot.pt | e_ suporte@maidot.pt | t_ +351 218 640 637

 

AVISO DE CONFIDENCIALIDADE: Esta mensagem, assim como os ficheiros eventualmente anexos, é confidencial e reservada apenas ao conhecimento da(s) pessoa(s) nela indicada(s) como destinatária(s). Se não é o seu destinatário, ou se  lhe foi enviada por erro, solicitamos que não faça qualquer uso do respectivo conteúdo e proceda à sua destruição, notificando o remetente.

LIMITAÇÃO DE RESPONSABILIDADE: A segurança da transmissão de informação por via electrónica não pode ser garantida pelo remetente, o qual, em consequência, não se responsabiliza por qualquer facto susceptível de afectar a sua integridade.

CONFIDENTIALITY NOTICE: This message, as well as existing attached files, is confidential and intended exclusively for the individual(s) named as addressees. If you are not the intended recipient, or if it was sent to you by error, you are kindly requested not to make any use of its contents and to proceed to the destruction of the message, thereby notifying the sender.

DISCLAIMER: The sender of this message can not ensure the security of its electronical transmission and consequently does not accept liability for any fact which may interfere with the integrity of its content.

 

De: Pär Thernström [mailto:notifications@github.com] 
Enviada: 27 de fevereiro de 2019 20:59
Para: bonny/WordPress-Simple-History <WordPress-Simple-History@noreply.github.com>
Cc: pedlima <contacto@pedrolima.info>; Author <author@noreply.github.com>
Assunto: Re: [bonny/WordPress-Simple-History] Upload Portuguese (Portugal) translation (#157)

 

Thanks Pedro! That's great that to hear that you have translated the plugin to Portuguese.

The tranlation of the plugin takes place over at
https://translate.wordpress.org/locale/pt/default/wp-plugins/simple-history.

Any change you could add or import your translations there?
