### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function _acf_get_field_by_id() in loggers/Plugin_ACF.php:374

### ISSUE THREAD

**Issue by AkeraYoui** [bonny/WordPress-Simple-History#158]
Hi,

I got this issue with acf version 5.7.11.

I think the simple fix to this issue, is by changing : 
` _acf_get_field_by_id()`
to the new function : 
`acf_get_field()`

Thanks for the great job.

**Comment by bonny** [comment]
Fixed in version 2.29.2, please give it a try!
