### ISSUE TITLE
Make shortcodes (and functions) for Simple history

### ISSUE THREAD

**Issue by samjco** [bonny/WordPress-Simple-History#159]
I love the way Simple history captures and log events.

However, I would love it even more if I can separate those even to certain users or certain events. Because sometimes I want to just capture the Revisions done by ALL user and some.

For example, If we can do something like this:

`[simplehistory events="all" posttypes="all" users="all" ]`
This example would do simplehistory as it does already by default.

`[simplehistory events="revisions" posttypes="posts, pages" users="1, 3" ]`
All to do with event of revisions the posttypes of posts,pages and for users id 1,3

These are just some examples

**Comment by bonny** [comment]
Not sure I follow, where do you put these shortcodes?

**Comment by samjco** [comment]
@bonny 
No... I was given an example of shortcodes that would be nice to have!

**Comment by bonny** [comment]
Ok, but if those shortcodes did exist you would use them on the frontpage of a website and everyone could see the log?

**Comment by samjco** [comment]
Yes. And or I would even use them in the dashboard as well!

**Comment by bonny** [comment]
Ok! Thanks for the explanation. I don't think this is something that the plugin should do by default at the moment, it feels risky to show it on the front of a website.

**Comment by samjco** [comment]
But what about the use in the backend dashboard?

**Comment by bonny** [comment]
Hm.. where do you enter shortcodes in the backend? Not sure I've ever done that!

**Comment by samjco** [comment]
Sorry I was referring to the Functions for the dashboard .... 
And is it possible to get some direction as to how I can make my own shortcodes off of your functions?

**Comment by bonny** [comment]
There is a class called `SimpleHistoryLogQuery` that you can use to get events from the audit log. Something like this should get you started:

```
$args = array(
    'posts_per_page' => 1,
);
$logQuery = new SimpleHistoryLogQuery();
$queryResults = $logQuery->query( $args );
```

**Comment by samjco** [comment]
THANKS!!
