### ISSUE TITLE
Feature request: Option 'db_purge_days_interval' in Settings page

### ISSUE THREAD

**Issue by twaiiiin** [bonny/WordPress-Simple-History#161]
Hello,

Feature request: An option in the Settings page to choose how many days the logs are kept.
It's possible to do it with the `simple_history/db_purge_days_interval` filter but it would be nice and easier for the end-user to have an option for that.

Thank you for your great work.

**Comment by bonny** [comment]
Thanks for the feature request. At the moment I'll stick with the filter to keep the number of options down.
