### ISSUE TITLE
Feature request: Display Simple History in the frontend

### ISSUE THREAD

**Issue by twaiiiin** [bonny/WordPress-Simple-History#162]
Hello,

Feature request: A way to display a "Post History" (for a specific post) or a "Site History" (for all posts) in the frontend. Maybe a PHP function where developers can select/filter a lever of severities or an initiator.

Thank you for your great work.

**Comment by samjco** [comment]
This sound similar to my request :)
https://github.com/bonny/WordPress-Simple-History/issues/159#issue-410929131

**Comment by bonny** [comment]
Thanks for the feature request. I still feel that Simple History should focus on showing things in the admin area and not on the frontend. But please check out my comment on #159 for an example how to get started on getting the events yourself. With a bit more code you could get a log on the frontend yourself.
