### ISSUE TITLE
Improvement: Log taxonomy name/label instead of slug

### ISSUE THREAD

**Issue by twaiiiin** [bonny/WordPress-Simple-History#164]
Today, when I add/modify/delete a taxonomy term, Simple History logs:

> Added term "term_name" in taxonomy "taxonomy_slug"

It probably should be :

> Added term "term_name" in taxonomy "taxonomy_name"

OR

> Added term "term_name" in taxonomy "taxonomy_label"

**Comment by bonny** [comment]
Good catch. Will be fixed in next version.
