### ISSUE TITLE
How to show diff?

### ISSUE THREAD

**Issue by nrg-jeff** [bonny/WordPress-Simple-History#165]
Doesn't show the diff made to the page as shown in the screenshot. I have to go individually into each page and click on revision history to see the difference. Is there a way to show the diff on the dashboard?

![Screen Shot 2019-03-20 at 1 08 20 PM](https://user-images.githubusercontent.com/45057074/54715732-5e4ad300-4b11-11e9-9cb4-db98c9305b96.png)

**Comment by bonny** [comment]
This was probably because of Gutenberg. Try again with latest version (2.30 or later) and it should work.
