### ISSUE TITLE
Simple History and Participants Database plugin

### ISSUE THREAD

**Issue by gruntek** [bonny/WordPress-Simple-History#167]
Is there a simple way to add Participant Database events like record edit to Simple History?

**Comment by bonny** [comment]
Yes, probably there is. The Participants Database plugins does have an API:
https://github.com/bonny/WordPress-Simple-History/blob/master/examples/examples.php
and together with the Simple History API (see https://github.com/bonny/WordPress-Simple-History/blob/master/examples/examples.php for examples) you should be able to log whatever you want. 

You can use the support forum at https://wordpress.org/support/plugin/simple-history/ if you need further help.
