### ISSUE TITLE
Integrate Simple History plugin with Git repository

### ISSUE THREAD

**Issue by JoshFialkoff** [bonny/WordPress-Simple-History#175]
Is it possible to add Simple History logs to Github so that we can track key database changes in Git? So that this sort of history would be stored in the site's repository:
![Simple_History_‹_ForwardJump_Marketing_—_WordPress](https://user-images.githubusercontent.com/3923170/58478877-0f2ea900-8125-11e9-9698-2694aa6617ea.png)

What is the best way to do this?

**Comment by bonny** [comment]
Hm.. not sure I follow what you want to do. Can you explain it a bit more?

**Comment by PauloBoaventura** [comment]
Hello @bonny and participants

What I would like is to update the plugin directly from Github, could this be done via API? Or a CRON with a script ((.sh))?
Can we do this in a practical and safe way?
Any suggestion?

Or ... SimpleHistory can notify a warning on the plug-in panel. Notifying the update on GitHub.


_

> I don't know if it's correct, but the topic is the same as it would be created. So, I'm going to use this one. If I'm doing it wrong. Excuse me.

_

**Comment by bonny** [comment]
> Hello @bonny and participants
> 
> What I would like is to update the plugin directly from Github, could this be done via API? Or a CRON with a script ((.sh))?
> Can we do this in a practical and safe way?
> Any suggestion?
> 
> Or ... SimpleHistory can notify a warning on the plug-in panel. Notifying the update on GitHub.
> 
> _
> 
> > I don't know if it's correct, but the topic is the same as it would be created. So, I'm going to use this one. If I'm doing it wrong. Excuse me.
> 
> _

@PauloBoaventura: If you want auto updates you should download the plugin from the [WordPress Plugin Directory](https://wordpress.org/plugins/simple-history/) or user [Composer](https://getcomposer.org/) to manage the updates.
