### ISSUE TITLE
How to use filter to move simple_history_page to "Tools"

### ISSUE THREAD

**Issue by thomasmalley** [bonny/WordPress-Simple-History#182]
My Question is regarding #140 & #168 

I can't quite figure out how to apply the filter. Can you give me any advice?

Best regards!

**Comment by bonny** [comment]
It should be enough to add this snippet to your `functions.php` file:

```
// Move Simple History log sub page from the "Dashboard" menu to the "Tools" menu.
add_filter('simple_history/admin_location', function ($location) {
	$location = 'tools';
	return $location;
});
```

If you need more help or have any other questions feel free to use the [support forum](https://wordpress.org/support/plugin/simple-history/).
