### ISSUE TITLE
echo php in top of wp admin environment 

### ISSUE THREAD

**Issue by Joeri-Abbo** [bonny/WordPress-Simple-History#190]
![image](https://user-images.githubusercontent.com/34270045/71978320-516fab00-321b-11ea-8ad7-3841b8c28cf8.png)
I am gettting this error on the top of my wordpress site. I found it in fileEditsLogger.php in this plugin. I dont get the reason why this is would be dumpt in the top.

**Comment by bonny** [comment]
Where do you see this? On what page?

**Comment by Zarath0s** [comment]
I get this message on a setting page of polylang pro.

**Comment by bonny** [comment]
And if you disable Simple History you get no error or strange output on that page?
What version of WordPress + PHP are you using?

**Comment by Zarath0s** [comment]
If i disable Simple History I do not get the error. I have the error on my local dev env and on production. This are de sitehealth settings of my local env.
### wp-core ###

version: 5.3
site_language: en_US
user_language: en_US
timezone: +01:00
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 24
dotorg_communication: true

### wp-mu-plugins (4) ###

Bedrock Autoloader: version: 1.0.0, author: Roots
Disallow Indexing: version: 1.0.0, author: Roots
Register Theme Directory: version: 1.0.0, author: Roots
WP Migrate DB Pro Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (20) ###

ACF Content Analysis for Yoast SEO: version: 2.3.0, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast
Admin Menu Editor: version: 1.9.2, author: Janis Elsts (latest version: 1.9.3)
Advanced Custom Fields PRO: version: 5.8.7, author: Elliot Condon
Classic Editor: version: 1.5, author: WordPress Contributors
Duplicate Post: version: 3.2.3, author: Enrico Battocchi (latest version: 3.2.4)
Intuitive Custom Post Order: version: 3.1.2, author: hijiri
Old Style Admin UI: version: 1.0.3, author: Digital Shadow
Polylang Pro: version: 2.6.8, author: WP SYNTEX
Redirection: version: 4.5.1, author: John Godley (latest version: 4.6.2)
SearchWP: version: 3.1.6, author: SearchWP, LLC (latest version: 3.1.8)
SearchWP Custom Results Order: version: 1.1.3, author: SearchWP, LLC
SearchWP Polylang Integration: version: 1.2, author: Jonathan Christopher
SearchWP Redirects: version: 1.3, author: SearchWP, LLC
Simple History: version: 2.33, author: Pär Thernström (latest version: 2.33.2)
Theme and plugin translation for Polylang (TTfP)(Rodesk Fork): version: 1.0.1, author: Joeri Abbo
Unbounce Landing Pages: version: 1.0.44, author: Unbounce
User Role Editor Pro: version: 4.54, author: Vladimir Garagulia (latest version: 4.54.1)
WP Migrate DB Pro: version: 1.9.8, author: Delicious Brains
WP Migrate DB Pro Media Files: version: 1.4.14, author: Delicious Brains
Yoast SEO: version: 12.6.2, author: Team Yoast (latest version: 12.8)

### wp-plugins-inactive (2) ###

Transients Manager: version: 1.8, author: Pippin Williamson
WP Crontrol: version: 1.7.1, author: John Blackbourn & crontributors

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 19.2.0 x86_64
httpd_software: nginx/1.17.7
php_version: 7.2.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 600
memory_limit: 128M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.68.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false

### wp-database ###

extension: mysqli
server_version: 10.4.11-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
