### ISSUE TITLE
Failed Email Logins Generate Two Errors

### ISSUE THREAD

**Issue by Enchiridion** [bonny/WordPress-Simple-History#191]
When I log into my site using a valid email address and an incorrect password, the plugin generates 2 failed login events.  This is due to WordPress first checking the name/pass pair as a username/password, then if it fails, as an email/password, each time running the `wp_authenticate_user` filter.  This plugin logs both failures separately, they really should only count as 1 failed login.

**Comment by bonny** [comment]
I have not seen this behavior before. Do you have any other plugins installed that modify the user or login process in any way?
