### ISSUE TITLE
Feature request: Stop logging failed logins by default

### ISSUE THREAD

**Issue by blogjunkie** [bonny/WordPress-Simple-History#193]
I’ve begun having problems with Simple History because it’s database use is too heavy. Having looked into it, I realize it’s because SimpleUserLogger is recording lots and lots of failed logins – thanks to all the bots that try to guess the site passwords. On a typical site, the Debug tab reports that 99% of the database rows are for SimpleUserLogger.

I see the utility of SimpleUserLogger, but it’s becoming a problem and I believe that most users would prefer to track failed logins with a security plugin.

Please consider to have stop logging failed logins by default, and a setting be added to enable it for those who want it. Thank you

**Comment by bonny** [comment]
Thanks for the feedback. Do you get lots of failed logins for known users or mostly for unknown users? I do understand that this is a big problem for users who get very large amount of login attempts, while the feature is still very nice to have I think. So need to find the best solution..

**Comment by blogjunkie** [comment]
Its for known users mostly. It looks like bots trying to guess the passwords for site users.

**Comment by bonny** [comment]
This is atm possible to control using the [Extended Settings Add-on](https://simple-history.com/add-ons/extended-settings/#limit-number-of-failed-login-attempts).
