### ISSUE TITLE
Custom date range in Dates: menu displays in US/non-WP date format

### ISSUE THREAD

**Issue by rklrkl** [bonny/WordPress-Simple-History#197]
I'm in the United Kingdom and our WordPress install has a Europe/London timezone and a global date format of d/m/Y (e.g. 21/04/2020) configured in Dashboard -> Settings -> General.

However, the "Custom date range..." option in the Dates: menu of Simple History's search page shows the start and end dates in US format (MM-Mmm dd, Y) rather than either following the date format of the locale or indeed even the global WP date format as mentoned above.

**Comment by bonny** [comment]
Can't reproduce this, if you still have this problem please comment and post a screenshot of the problem.
