### ISSUE TITLE
CSS styling on pagination buttons are a bit off. Are you open adjusting it?

### ISSUE THREAD

**Issue by claytoncollie** [bonny/WordPress-Simple-History#200]
Hi there. I was looking at the pagination buttons and was wonder if we can remove the custom classes and styling and replace them with Core utility classes. Is that something you are open to? I don't want to break backwards compatibility. Hopefully, people don't have any custom styling for this portion of the plugin. Let me know and I'll send a PR.

**Comment by bonny** [comment]
Core classes would be best, I agree. I can't remember why I did not use them when I created the pagination. Feel free to send a PR!
