### ISSUE TITLE
Feature request: Allow loggers to be enabled/disabled

### ISSUE THREAD

**Issue by rklrkl** [bonny/WordPress-Simple-History#204]
In the Settings -> Debug tab of Simple History, the set of current loggers is displayed along with some useful info. It would be extremely nice if there was a tick box column as well to enable or disable each logger individually (you can default them all to enabled, which makes sense). These should ideally be controllable by WP-CLI as well.

The logger that generates by far the most entries is the first one: "User Logger", but it lumps everything into one logger - I think that logger needs to be split up, especially if an enable/disable feature is added like I'm requesting.

Successful user logins/logouts should be controllable separately from failed user logins, IMHO - the latter can generate tons of entries from hacker bots and some sites might want to log only successful logins/logouts and leave other tools (WP fail2ban or whatever) to deal with failed logins.

Personally, I even doubt the usefulness of logging anything to do with user logins/logouts/failed logins, especially if you have another security plugin handling those. I'm much more interested in changes to the system (which log all the info you need) than when a user logged in or out.

**Comment by JoryHogeveen** [comment]
I also think this would greatly benefit this plugin.
It would allow to finetune what is being logged and what is not. Might even be more awesome to allow loggers to have it's own sub settings.

**Comment by bonny** [comment]
Thanks for the suggestion. I do agree that something like this would be useful.

**Comment by bonny** [comment]
There is now an add-on that implements this, it's called "Message Control":
https://simple-history.com/add-ons/extended-settings/#message-control

![Screenshot of message control setting for simple history](https://github.com/bonny/WordPress-Simple-History/assets/221570/cb567abb-9fef-4872-92e3-a62b823cc222)
