### ISSUE TITLE
Logging of category and tag taxonomy attachment

### ISSUE THREAD

**Issue by claytoncollie** [bonny/WordPress-Simple-History#214]
On a fresh install of WP with this plugin installed, I am creating a Post and hitting publish. Works great. 

Then I update the post_content and featured image. Again, logs those well. Looks great. 

Then I assign a category or post_tag and refresh the History logger, and it says "Custom Field 1 changed". 

Is this normal? Shouldn't built-in taxonomies be supported a little better? Asking not in a critique but if i am doing it right. I see where it logs that a term was created inside the taxonomy but nothing about it being attachd to a post.

**Comment by bonny** [comment]
Took a while but I can confirm this bug. Working on a fix.

**Comment by bonny** [comment]
Almost done. This will be great!

![CleanShot 2024-01-22 at 21 09 54@2x](https://github.com/bonny/WordPress-Simple-History/assets/221570/e2719b68-3360-403e-80db-2d7ba796bdf0)

**Comment by rodrigo-arias** [comment]
@bonny It's great that you brought back these old issues, I think some of those can boost Simple History. I left a comment on https://github.com/bonny/WordPress-Simple-History/issues/245#issuecomment-1904815400 which I think is the other big gap.
