### ISSUE TITLE
Plugin does not log edits to custom post types using Gutenberg Block Editor

### ISSUE THREAD

**Issue by claytoncollie** [bonny/WordPress-Simple-History#215]
https://github.com/bonny/WordPress-Simple-History/blob/66b8c7f94c8acae7a93d131e223561c29d247a37/loggers/SimplePostLogger.php#L49

I am not able to log edits made by custom post type entries when using the block editor and I think this line is the issue. I am writing the contents of this variable to my log and it is only showing built-in post types. I am trying very hard to write a patch for this so it grabs all post types, built-in, and custom but am running into a wall. I think I am not able to see custom post types because they are registered in `init` when this `loaded` method is loading beforehand on `after_setup_theme`

https://github.com/bonny/WordPress-Simple-History/blob/66b8c7f94c8acae7a93d131e223561c29d247a37/inc/SimpleHistory.php#L102

Does that sound right?

My patch would look something like this. Note: this does not work.

```
// Get WordPress default post types.
$builtin = get_post_types( [ '_builtin' => true ], 'object' );

// Get all custom post types.
$custom = get_post_types( [ '_builtin' => false ], 'object' );
        
// Merge all post types.
$post_types = array_merge( $builtin, $custom );
```

Any guidance would be appreciated. I can submit a PR once we get a solution.

**Comment by claytoncollie** [comment]
@bonny Any idea about this one? Can you give it a quick test on a custom post type with the block editor?

**Comment by bonny** [comment]
Closing, I believe this one is fixed right?
