### ISSUE TITLE
Restrict history view by User

### ISSUE THREAD

**Issue by samjco** [bonny/WordPress-Simple-History#229]
Is there a way to restrict all users except one?

I've seen this code, but this restricts by role...
```

/**
 * Change capability required to view main simple history page.
 * Default capability is "edit_pages". Change to for example "manage options"
 * to only allow admins to view the history log.
 */
add_filter('simple_history/view_history_capability', function( $capability ) {
	$capability = 'manage_options';
	return $capability;
});
```

**Comment by bonny** [comment]
That would be possible I think. Could you post your question over at [the support forum](https://wordpress.org/support/plugin/simple-history/) so I could answer it over there, so other can find the question and the answer in the future?
