### ISSUE TITLE
Improving the Settings page

### ISSUE THREAD

**Issue by AlirezaAmoupour** [bonny/WordPress-Simple-History#234]
**Hi, dear friend(s)**
I've been using the plugin for my test website, and since we are about 10 users as admins, yet the amount of database rows are huge. Although it is a **admin-side** plugin, but we know that _milliseconds_ matter a lot.

I would really love to contribute but unfortunately don't have enough time right now! :(
It would be great if there was options in the **Settings Page** that we can choose for the plugin to show in log pages. For example, I don't need the logs about **posts** or **comments** or plugin **updates**, so I want to **_disable_** them and save some **database optimization**.

I don't know if it's a hard request or not, but I think other might have this problem too.

**Thank you so much!**

**Comment by bonny** [comment]
Thanks for the issue @AlirezaAmoupour. 

I beleive there is a similar issue here:
https://github.com/bonny/WordPress-Simple-History/issues/204
So I will close this one and you can follow the other one for updates and discussion!
