### ISSUE TITLE
Styling is off in the compare screen

### ISSUE THREAD

**Issue by ironland** [bonny/WordPress-Simple-History#246]
All changes show like this, so there's maybe soemthing wrong with the css?
Plugin v 2.41.2
WP v 5.7

![image](https://user-images.githubusercontent.com/6129903/111821695-9f864100-88eb-11eb-9325-7ee77ebbd164.png)

**Comment by bonny** [comment]
Thanks for the bug report. It sounds like it's the same issue as this one.
https://wordpress.org/support/topic/issue-with-changes-in-post-pages-and-faqs/

I have not been able to reproduce it yet.

Do you have any other plugins installed when you get that error?

**Comment by NekoJonez** [comment]
I have been toying with the styles.css and I noticed that I have been rusty with CSS... @bonny Which CSS file is this function using?

**Comment by NekoJonez** [comment]
Alright, on a clean WP install... I was able to reproduce it :(

**Comment by bonny** [comment]
Ok, I was able to reproduce this now. I think I tested with to small changes or something the last time I tested. I will work on a fix, stay tuned..

**Comment by bonny** [comment]
This will be fixed in the next version.

**Comment by bonny** [comment]
Fixed in 2.42.0.
