### ISSUE TITLE
Removed plugins don't show up in the log

### ISSUE THREAD

**Issue by NekoJonez** [bonny/WordPress-Simple-History#247]
As the title says. When an user removes a plugin, it's not displayed in the log.

**Comment by bonny** [comment]
How are the plugins removed?

**Comment by NekoJonez** [comment]
I remove them via the normal WP plugin way... Go to the plugins section and click "deactivate" and then "delete".

**Comment by bonny** [comment]
I just tried this and when I deactivate the plugin it is logged, but when I delete the plugin files nothing is logged. I guess that could be something that should be logged.

**Comment by NekoJonez** [comment]
Excellent. Thank you for adding this as a feature on the roadmap :-)
