### ISSUE TITLE
Enable setting Google Map API Key in the Setting tab

### ISSUE THREAD

**Issue by civita** [bonny/WordPress-Simple-History#249]
Hello,
Thanks for developing this plugin. I've learned a lot by creating my own logger! I noticed that the feature showing Google Map in IP field has been commented out since this [commit](https://github.com/bonny/WordPress-Simple-History/commit/e7e9c0a12bf4a77854bc53a8224950c399497729) due to the requirement of API key.

If there is an text filed for users to input their own Maps API key, it would be very nice (attached screenshot for reference)!

![Screenshot from 2021-05-06 03-39-43](https://user-images.githubusercontent.com/14911217/117200174-bb06c600-ae1d-11eb-9b84-693c433277c6.png)

**Comment by bonny** [comment]
Thanks for the suggestion. A way to enter the API key would be nice indeed. Either in the settings page or with a constant that can be added to `wp-config.php`, like `SIMPLE_HISTORY_GOOGLE_MAPS_API_KEY=abc`.

**Comment by bonny** [comment]
The next version will have a filter to set a Google Map API key. Usage is like this:

```
add_filter(
    'simple_history/maps_api_key',
    function() {
        return 'your key';
    }
);
```
