### ISSUE TITLE
I have a PHP notice with the Web stories plugin by google 

### ISSUE THREAD

**Issue by galyb** [bonny/WordPress-Simple-History#260]
I get a php notice : Trying to access array offset on value of type null in plugins/simple-history/loggers/Plugin_ACF.php on line 272.

I saw that the problem has already been fixed [link](https://github.com/bonny/WordPress-Simple-History/pull/248) but I only encounter the problem with the plugin [Web Stories by google](https://wordpress.org/plugins/web-stories/).

To trigger the error, all you have to do is edit a store or create a new one. I have no problem with posts and customs posts.

Here are the different versions that I use.
PHP version 7.4.6
WP 5.7.2
simple history 2.42.0
ACF 5.9.8
Web stories 1.9.0

Thanks you.

**Comment by bonny** [comment]
Unable to reproduce this. Please open again if error still occurs.
