### ISSUE TITLE
New version in WordPress Packagist

### ISSUE THREAD

**Issue by rodrigo-arias** [bonny/WordPress-Simple-History#269]
Hi @bonny thanks for your work on Simple History. This is not actually a bug but a request to release a new version in WP Packagist.

Since version 2.42 some warnings with ACF https://github.com/bonny/WordPress-Simple-History/pull/248 and PHP 8 https://github.com/bonny/WordPress-Simple-History/pull/263 have been fixed, I would be grateful if you could release a new version with these updates.

Thanks

**Comment by bonny** [comment]
Hi @rodrigo-arias ! Thanks for reminding me about this :) I will try to release a new version this week.
