### ISSUE TITLE
Searching fails on translations

### ISSUE THREAD

**Issue by S8nsick66** [bonny/WordPress-Simple-History#277]
I have Wordpress in Swedish. 
The log shows things like "Misslyckades att logga in med användarnamnet ...." but searches for "misslyckades" give no results.
Searching for "failed" finds those items though.

**Comment by bonny** [comment]
The message stored is

> Failed to login with username "{login}" (incorrect password entered)

while the message shown is dependent of the current language, so for Swedish it will be

> Misslyckades att logga in med användarnamnet ”<username>” (felaktigt lösenord angavs)

So when searching for "misslyckades" that word does not exist in the db.

Solution:

- When searching
  - Get all translations for domain `simple-history`: `$translations = get_translations_for_domain( 'simple-history' );`
  - For each translation
    - check if "misslyckades" matches anything inside the key "translations"
    - if it matches then add the singular version of the translation as the search query


Example of contents in `$translations`:

```
[Failed to login with username "{login}" (incorrect password entered)] => Translation_Entry Object
    (
        [is_plural] => 
        [context] => 
        [singular] => Failed to login with username "{login}" (incorrect password entered)
        [plural] => 
        [translations] => Array
            (
                [0] => Misslyckades att logga in med användarnamnet ”{login}” (felaktigt lösenord angavs)
            )

        [translator_comments] => 
        [extracted_comments] => 
        [references] => Array
            (
            )

        [flags] => Array
            (
            )

    )
```

**Comment by bonny** [comment]
No, better method:

```

- Get a list of all loggers that a user has access to: `$loggers_user_can_read = $this->simple_history->get_loggers_that_user_can_read();`
- For each logger
  - Check all messages
    - If translated_text contains the word searched for
    - get the message_key for the found message, i.e. `user_login_failed`
    - include the message_key in the search
      - replace the search to only contain that message key?

Should work, but needs some testing. It will not be perfect. But search never is 🤷 
.

```

**Comment by bonny** [comment]
Progress! LGTM 🤷 

![search before](https://github.com/bonny/WordPress-Simple-History/assets/221570/d8aa7c62-a592-44b1-9f09-6538bf9c5233)

![search after](https://github.com/bonny/WordPress-Simple-History/assets/221570/122837e2-6a09-4abd-86b8-ef72e02199d7)

**Comment by S8nsick66** [comment]
Looking wonderful! Great job :)
