### ISSUE TITLE
Missing Name on Query History

### ISSUE THREAD

**Issue by toniojst** [bonny/WordPress-Simple-History#299]
Hi when i query for history data on frontend i dont get in message (context) real data about name of Plugin or name of Person,.. for example i get this: “Edited the profile for user “{edited_user_login}” ({edited_user_email})”, but in WP-admin working normaly i get this data. What can be wrong?

If i try to output data with next code which is an example in documentation, my site event not load properly.
```
foreach ( $queryResults['log_rows'] as $row ) {
	$header_output = $this->sh->getLogRowHeaderOutput( $row );
	$text_output = $this->sh->getLogRowPlainTextOutput( $row );
	$details_output = $this->sh->getLogRowDetailsOutput( $row );

	// ...
}
```
Right now  I output data with next code, but problem is that i get -> Deleted plugin “{plugin_name}” <- isted of eg. -> Deleted plugin “ACF” <-
```
foreach ( $queryResults['log_rows'] as $row ){
    echo $row->message;	
}
```
What can be problem?

**Comment by bonny** [comment]
Please see the answer at the support forum:
https://wordpress.org/support/topic/missing-name-on-query-history/#post-15819682
