### ISSUE TITLE
File Edits logger has stopped working

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#303]

**Comment by firmlab** [comment]
Any update on this Bug?

Today I tried to test this File logger, it seems still not working

**Comment by bonny** [comment]
No updates yet, you can follow this issue to get notified when any changes happen.

**Comment by bonny** [comment]
> Any update on this Bug?
> 
> Today I tried to test this File logger, it seems still not working

@firmlab this was fixed in version 4.15.1:
https://wordpress.org/plugins/simple-history/#developers
