### ISSUE TITLE
Temporarily disable logging

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#307]
Add a way to disable logging during a short while.

This can be useful when:

- Importing many things using PHP the log can be overwhelmed with data.

- Making many changes on a site, for example changing hundreds of affiliate links.

Only admins should be allowed to modify this using the GUI. And when the setting is enabled a message should appear in the log + maybe as an "notification" on the log screen.

Enable in the GUI in the settings or with code. Something like `Simple_History::disable_logging()` and then `Simple_History::enable_logging()`.

Or a filter/action, something like: `do_action( 'simple_history/disable_logging' ) `;

**Comment by johnbillion** [comment]
In my Query Monitor plugin I ended up doing this via an action so there's no need for a third party plugin to first call `method_exists()` for example.

https://wordpress.org/plugins/query-monitor/#can%20i%20prevent%20query%20monitor%20from%20collecting%20data%20during%20long-running%20requests%3F

The underlying methods to disable data collection in Query Monitor itself are hooked into this action.

**Comment by bonny** [comment]
That's much better, I will do something similar. Thanks for the suggestion!
