### ISSUE TITLE
Undefined array key "attachment_parent_title" in SimpleMediaLogger.php

### ISSUE THREAD

**Issue by jhard** [bonny/WordPress-Simple-History#313]
Btw, https://simple-history.com/ is showing some deprecation warnings.

**Describe the bug**
Ajax Call to `/wp-admin/admin-ajax.php?action=simple_history_api&type=overview&format=html&posts_per_page=5&paged=1&dates=lastdays%3A30` produces an E_WARNING in simple-history/loggers/SimpleMediaLogger.php:116 `Undefined array key "attachment_parent_title"`

The stack trace inside simple-history is
```
simple-history/loggers/SimpleMediaLogger.php:116
simple-history/inc/SimpleHistory.php:2357
simple-history/inc/SimpleHistory.php:2460
simple-history/inc/SimpleHistory.php:666
```

**Expected behavior**
No warning to be produced.

**System information (please complete the following information):**
 - Simple History version: 3.3.0
 - WordPress version: 6.0.2
 - PHP version: 8.0.20

**Comment by bonny** [comment]
Thanks for the bug report, I will fix in an upcoming update.
