### ISSUE TITLE
Wrong role is shown for user added to subsite on a multisite

### ISSUE THREAD

**Issue by MannyAdumbire** [bonny/WordPress-Simple-History#325]
I added someone with the "Administrator" Role.
Simple history says:
Created user xxx with role **subscriber**

I confirmed they were correctly added as an Administrator and are shown as an Administrator on the Users screen.

**To Reproduce**
1. Got to **Users** on a subsite of a multisite-enabled WordPress install.
2. Select **Add New**
3. Fill in any user details and give them an "Administrator" Role.
4. From admin menu select **Simple History**

**Expected behavior**
For Simple history to say:
Created user xxx with role **administrator**

**System information (please complete the following information):**
 - WordPress version: 6.1
 - PHP version: 8.0.26

**Comment by bonny** [comment]
Thanks for the bug report @MannyAdumbire. I was able to reproduce this.

**Comment by bonny** [comment]
Probably due to this in `ms-functions.php`:

```
// Newly created users have no roles or caps until they are added to a blog.
delete_user_option( $user_id, 'capabilities' );
delete_user_option( $user_id, 'user_level' );
```
