### ISSUE TITLE
Feature request: Add ability to disable authentication login reports for none admin users

### ISSUE THREAD

**Issue by ivcreative** [bonny/WordPress-Simple-History#327]
We have a site that allows students to login in as subscribers to read private articles, there are times we get 1000s of logins into the system in a few seconds when we have the classes open, those logins get reported in simple history, the issue is that our binary log from Mysql grows like crazy and is making the servers run out of space for these logs, we increased a lot of space but for now when these logins are added to the database the logs becomes around 13gb in a minute, the only way we had to prevent this was to turn off the simple history plugin.

We like the plugin and would like to request a way to have logins by role not get logged into the report this generates, we mostly use it to keep an eye on what editors or admins are changing on the site content.

**Comment by bonny** [comment]
Thanks for your feature request @ivcreative and also thanks for the detailed explanation of the issues you had.

While it's not possible at the moment to control this using the GUI, you can add a snippet of PHP code to your `functions.php` or similar to stop the logins from subscriber to be stored in the log. For example this snippet disables logging of login/logout activity performed by users with role subscriber:

```php

/**
 * Do not log login/logout activity from users
 * with set roles, for example "subscriber".
 */
add_filter(
    'simple_history/log/do_log',
    function ($do_log = null, $level = null, $message = null, $context = null, $logger = null) {
        // Bail if logger is not the logger that
        // takes care of logging user logins.
        if ($logger->slug !== 'SimpleUserLogger') {
            return $do_log;
        }

        // Used by successful logins and logouts.
        $user_id = $context['_user_id'] ?? null;

        // Used by failed logins.
        if (!$user_id) {
            $user_id = $context['login_id'] ?? null;
        }

        $message_key = $context['_message_key'] ?? null;

        // Bail if required data is not available..
        if (!$user_id || !$message_key) {
            return $do_log;
        }

        // Get role of user trying to login/logout.
        $user = get_user_by('id', $user_id);

        if (!$user) {
            return $do_log;
        }

        $user_roles_to_not_log = [
            'subscriber',
            // 'administrator',
            // ...,
        ];

        // Check if user role is among the ones to log.
        foreach ($user_roles_to_not_log as $one_role) {
            $user_has_role = in_array($one_role, $user->roles);
            if ($user_has_role) {
                // Do not log because user role is one of
                // the roles in $user_roles_to_not_log.
                $do_log = false;
            }
        }

        return $do_log;
    },
    10,
    5
);

```
