### ISSUE TITLE
Quantity of Products

### ISSUE THREAD

**Issue by 3ehrouz** [bonny/WordPress-Simple-History#334]
When an user change the quantity of a products Simple History shows that something is changed in that products but it dose not show that was the quantity who has been changed

**Comment by bonny** [comment]
@3ehrouz Are you using a plugin to handle products on your website? Then perhaps that plugin does not have support for Simple History.

**Comment by 3ehrouz** [comment]
Hi
I use WooCommerce for Wordpress

**Comment by bonny** [comment]
Simple History does currently not have support for WooCommerce. I hope to be able to add support in the future however.
