### ISSUE TITLE
Missing keys in array returned from `$hook_extra` in `upgrader_process_complete` filter called from `WP_Upgrader` class

### ISSUE THREAD

**Issue by NekoJonez** [bonny/WordPress-Simple-History#339]
Now, I'm also going to post this link here: https://wordpress.org/support/topic/strange-error-message-during-updates/
Since, maybe somebody who helped coding Simple History might also have a clue what's going on...

Are there similar bugs reported or known about? What could be causing these files to error ONLY while updating but working fine otherwise.

**Comment by bonny** [comment]
From the support forum:

> On one website, I get strange error messages when updating. They are just there… And the plugins shown are working fine.

> And the annoying thing is that it only shows this block when I update… (Which work successful too)

```
Warning: Undefined array key "action" in /customers/7/5/e/lucasgent.be/httpd.www/---/wp-content/plugins/envira-gallery-lite/envira-gallery-lite.php on line 602 
Warning: Undefined array key "type" in /customers/7/5/e/lucasgent.be/httpd.www/---/wp-content/plugins/simple-history/loggers/SimpleThemeLogger.php on line 279 
Warning: Undefined array key "type" in /customers/7/5/e/lucasgent.be/httpd.www/---/wp-content/plugins/simple-history/loggers/SimpleThemeLogger.php on line 209 
Warning: Undefined array key "type" in /customers/7/5/e/lucasgent.be/httpd.www/---/wp-content/plugins/simple-history/loggers/class-sh-translations-logger.php on line 49
```

The cause is filter `[upgrader_process_complete](https://developer.wordpress.org/reference/hooks/upgrader_process_complete/)` that usually
