### ISSUE TITLE
Some entries missing in the French PO file

### ISSUE THREAD

**Issue by davidbourguignon** [bonny/WordPress-Simple-History#36]
Dear Pär,

I discovered your great "Simple History" plugin today and installed it on a freshly updated French-speaking WP installation. It was very well translated overall. However, when clicking on "Simple History" in the "Dashboard" menu I bumped into a sentence in English: "1 event today from one user" which was not translated. And on the side, there was a "Filter history" form with all entries in English...

After checking the French PO file, I did not find any untranslated entries. Maybe this PO file has not be regenerated for a while from the source code, maybe these untranslated entries are still not considered as translatable... Is it normal?

I hope it helps. Thanks in advance, and happy holidays!

David.

**Comment by davidbourguignon** [comment]
Oops @bonny I did not notice your comment! My most sincere apologies. Do you still need help with this one? I can provide... :-)

**Comment by bonny** [comment]
@davidbourguignon: no worries. I actually just got an email from another french user regarding translation. I think that person wanted to translate, so hold your translation for a while and we'll se what happens. I'll ping you here again when I know more about the translation status!

**Comment by davidbourguignon** [comment]
Alright @bonny. Thanks!

**Comment by bonny** [comment]
There was an updated French translation in version 2.5. I hope it works - if not then please make a better one :)

**Comment by davidbourguignon** [comment]
Thanks a lot @bonny for the info. Everything looks fine! :-)

**Comment by bonny** [comment]
WordPress recently changed & improved the way translation works for plugins. Now a translator can edit the translations online. So if you (or anyone else reading this) want to make changes to the translation (no matter what language) you can now request to be a "Translation Editor".

More info here:
https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#translating-themes-plugins

**Comment by davidbourguignon** [comment]
Thanks a lot @bonny! But frankly I do not really get this new translation system... The list of announcements posted by users on https://make.wordpress.org/polyglots/ seems a very inefficient way to handle this issue. Why WordPress is not adopting Transifex or some other good i18n platform? Let's wait and see?

**Comment by bonny** [comment]
Yeah, I don't quite get it myself either. But it seems to be the way it's gonna work from now on. :/
