### ISSUE TITLE
Suggestion: Allow for a cleaner way to selectively shortcut loggings

### ISSUE THREAD

**Issue by aanndryyyy** [bonny/WordPress-Simple-History#373]
Background information: I am using Simple History as a logging framework where I want to disable all built-in logging functionality. I have also set the logging database to never purge (days = 0) and disabled the manual clearing button.

Currently the filters for `simple_history/log/do_log` are returning after each `apply_filters()` call. I propose to make it return only at the end, so instead of this:

```php
add_filter( 'simple_history/log/do_log', 'my_big_function_to_filter_loggers' );
```

it would be possible to do this:
```php
add_filter( 'simple_history/log/do_log', '__return_false' ); // Disable all loggers
add_filter( 'simple_history/log/do_log/MyCustomLogger', '__return_true' ); // Allow only my custom logger
```

resulting in only MyCustomLogger logs being allowed. Or am I missing something and its already possible to do it like this? 🤔 

------

Reference to hooks: https://github.com/bonny/WordPress-Simple-History/blob/cd40b93ec28b0a058690c2e374cd1a8f05287bb0/loggers/class-logger.php#L1065-L1129

**Comment by bonny** [comment]
Nice solution! Never though about that but I'm happy you found a way.

**Comment by aanndryyyy** [comment]
@bonny seems that a PHP error is raised at https://github.com/bonny/WordPress-Simple-History/blob/cd40b93ec28b0a058690c2e374cd1a8f05287bb0/inc/class-simple-history.php#L2644

when using this solution:
```
add_filter( 'simple_history/core_loggers', '__return_empty_array' );
add_action( 'simple_history/add_custom_logger', '...' );
```

<details><summary>The PHP Error</summary>
<pre>
[18-Jul-2023 11:33:48 UTC] PHP Notice:  Undefined index: SimpleLogger in /wp-content/plugins/simple-history/inc/class-simple-history.php on line 2644
[18-Jul-2023 11:33:48 UTC] PHP Notice:  Trying to access array offset on value of type null in /wp-content/plugins/simple-history/inc/class-simple-history.php on line 2644
[18-Jul-2023 11:33:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_event_ip_number_headers() on null in /wp-content/plugins/simple-history/inc/class-simple-history.php:2644
Stack trace:
#0 /wp-content/plugins/simple-history/inc/class-simple-history.php(683): Simple_History\Simple_History->get_log_row_html_output(Object(stdClass), Array)
#1 /wp-includes/class-wp-hook.php(308): Simple_History\Simple_History->api('')
#2 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wp-admin/admin-ajax.php(188): do_action('wp_ajax_simple_...')
#5 {main in /wp-content/plugins/simple-history/inc/class-simple-history.php on line 2644
</pre>
</details> 

error is solved when allowing Simple_Logger to register:
```
add_filter( 'simple_history/core_loggers', fn() => [
    Loggers\Simple_Logger::class,
]);
```

The custom logger in this case is a very simple class that has one `$this->info_message()`. Error is not raised if the logs have been just cleared but immediately appears when adding a new log with the custom logger.

<img width="1240" alt="image" src="https://github.com/bonny/WordPress-Simple-History/assets/1809802/f3fdfa12-1e0c-4ec3-a075-f90079b684a1">

**Comment by bonny** [comment]
Ah, I never tried the plugin with no core loggers loaded at all. I will make a test and then a fix so I works in this scenario.

**Comment by bonny** [comment]
@aanndryyyy This will hopefully be fixed in the next version. If you want to test already you can test with the main branch here.

**Comment by bonny** [comment]
@aanndryyyy Please check if the latest version (4.4.0) of Simple History solved this.
