### ISSUE TITLE
Typos are alive

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#378]
Hello! 👋🏻 

The new workflow finds misspellings.
https://github.com/bonny/WordPress-Simple-History/actions/runs/5708063750/job/15465364527

Now it is up to you.

**Comment by bonny** [comment]
Thanks, I noticed and I will fix them! :)

**Comment by szepeviktor** [comment]
All right.

There are many more goodies over there.
https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows
You can spend weeks finding/fixing problems.
