### ISSUE TITLE
Sometimes always "1 new event"

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#397]
Sometimes the green bar comes up and says "1 new event". It only happens sometimes. Find out why and fix!

Reported for example here:
https://wordpress.org/support/topic/keep-getting-blank-event/

**Comment by bonny** [comment]
After some research I think this is happening on sites with MariaDB 10.6.12 (and possible others).

After installing a local test site with MariaDB the click on "+1 similar events" does not open anything.

On another test site I got access to there was strange grouping of similar events, some recent events got mixed with some really old.

Needs more investigation, but at least now I can reproduce it locally.

**Comment by frompton** [comment]
Can confirm seeing it on a site with
`mysql  Ver 15.1 Distrib 10.11.3-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper`
