### ISSUE TITLE
Debug tab, not translatable page title

### ISSUE THREAD

**Issue by kebbet** [bonny/WordPress-Simple-History#403]
**Describe the bug**
Page title is not translatable in this page `wp-admin/options-general.php?page=simple_history_settings_menu_slug&selected-tab=debug`
<img width="770" alt="image" src="https://github.com/bonny/WordPress-Simple-History/assets/11491369/2c0dd2f8-47ab-48da-acf7-5f077f10f26d">

This is due to the face that the helper function `get_settings_section_title_output` gets feeded with a string `Debug` instead of `__('Debug', 'simple-history' )`  [here](https://github.com/bonny/WordPress-Simple-History/blob/5cbad9c3b077120718592f65755244c3664fb588/templates/template-settings-tab-debug.php#L42).

**Comment by bonny** [comment]
Thanks @kebbet
