### ISSUE TITLE
esc_csv_field in php 8.1: substr(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by tobias-nygren-knowit** [bonny/WordPress-Simple-History#426]
**Describe the bug**
Gets a deprecation warnings in simple-history/dropins/class-export-dropin.php in PHP 8.1 when doing an Export to CSV. Add a null check to avoid this. 

**To Reproduce**
1. Activate PHP 8.1
2. Turn on WP_DEBUG and XDEBUG
3. Go to /wp-admin/options-general.php?page=simple_history_settings_menu_slug&selected-tab=export
4. Click on "CSV"
5. Click on "Download Export File"
6. Results: Fields with null is populated with the error: 
```
"<b>Deprecated</b>:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in <b>plugins/simple-history/dropins/class-export-dropin.php</b> on line <b>253</b><br />"
```

**Expected behavior**
I don't think null fields don't needs to be escaped . Maybe add something like this: 

```php
<?php // (...)
	public function esc_csv_field( $field ) {

		if ( null === $field ) {
			return $field;
		}
// (...)
```

**Screenshots**
-

**System information (please complete the following information):**
- WordPress version: 6.4.3
- PHP version: 8.1
- Installed plugins: Simple History 4.10.0

**Comment by bonny** [comment]
Thanks for the bug report, fixat i nästa version :)
