### ISSUE TITLE
Site throws an error (mails the error to admin)

### ISSUE THREAD

**Issue by patricksavalle** [bonny/WordPress-Simple-History#429]
**Describe the bug**
Fails to complete action of UMP plugin

**To Reproduce**

To keep your site safe, this link will expire in 1 dag. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress versie 6.4.3
Active theme: bodyhacker.network (version 1.0.0)
Huidige plugin: Simple History (versie 4.11.0)
PHP versie 8.0.30

Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 760 van het bestand /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/simple-history/loggers/class-user-logger.php. Foutmelding: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/simple-history/loggers/class-user-logger.php:760
Stack trace:
#0 /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/simple-history/loggers/class-user-logger.php(760): implode(', ', NULL)
#1 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/class-wp-hook.php(324): Simple_History\Loggers\User_Logger->on_user_register(382, Array)
#2 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(false, Array)
#3 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/user.php(2504): do_action('user_register', 382, Array)
#5 /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/indeed-membership-pro/admin/classes/MemberAddEdit.php(140): wp_insert_user(Array)
#6 /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/indeed-membership-pro/admin/includes/tabs/users.php(24): Indeed\Ihc\Admin\MemberAddEdit->save(Array)
#7 /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/indeed-membership-pro/admin/includes/manage-page.php(136): include_once('/var/www/vhosts...')
#8 /var/www/vhosts/bodyhacker.network/httpdocs/wp-content/plugins/indeed-membership-pro/admin/Main.php(191): require_once('/var/www/vhosts...')
#9 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/class-wp-hook.php(324): ihc_manage('')
#10 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#11 /var/www/vhosts/bodyhacker.network/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /var/www/vhosts/bodyhacker.network/httpdocs/wp-admin/admin.php(259): do_action('toplevel_page_i...')
#13 {main}
  thrown

**Comment by bonny** [comment]
Thanks! Do you by any change have any plugins installed that modify user roles or similar? A members plugin, a user role plugin... anything like that?
