### ISSUE TITLE
Plugin API Example links to 404 page

### ISSUE THREAD

**Issue by signo** [bonny/WordPress-Simple-History#44]
in the readme in the Plugin API section it says "See more examples at simple-history.com/docs" but the link takes the user to a 404 page in simple-history.com.

**Comment by bonny** [comment]
Ah, sorry about that. I redesigned the website and missed that part. Is it any specific stuff you need information about; maybe I can write something about that then.

**Comment by signo** [comment]
For a quick fix you could change it to reference the examples.php file,

**Comment by bonny** [comment]
Done!
