### ISSUE TITLE
[Feature Request]: Allow displaying the History page under Tools

### ISSUE THREAD

**Issue by vinkla** [bonny/WordPress-Simple-History#444]
I typically [hide the dashboard menu item](https://github.com/vinkla/wordplate/blob/a0f9e014588786aa57f4160b36f0deb4c9845fc8/public/themes/wordplate/functions.php#L40) to declutter the number of unused pages. A valuable feature would be the ability to move the history page to the tools menu. This would be particularly beneficial if you only want administrators accessing the history.

Also, thank you for making this plugin possible and maintaining it 🙌

**Comment by bonny** [comment]
@vinkla I never actually used this myself but way back someone else requested this and this was added then. Let me know if it works for you :)

> Add filter simple_history/admin_location that makes is possible to move the main page from the dashboard menu to any other menu page, for example the Tools menu. Fixes https://github.com/bonny/WordPress-Simple-History/issues/140. Example usage of filter:

```
// Move Simple History log sub page from the "Dashboard" menu to the "Tools" menu.
add_filter('simple_history/admin_location', function ($location) {
	$location = 'tools';
	return $location;
});
```

Related links:

- https://github.com/bonny/WordPress-Simple-History/blob/main/CHANGELOG.md#:~:text=Add%20filter%20simple_history/admin_location
- https://github.com/bonny/WordPress-Simple-History/issues/140
- https://github.com/bonny/WordPress-Simple-History/issues/182

**Comment by vinkla** [comment]
What a nostalgic find! This was also an issue by one of my friends 🙃 I should have searched more thoroughly. Thank you, Pär, for sharing the solution. Keep up the excellent work!
