### ISSUE TITLE
Add link to linklist below "All updates have been completed" message

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#453]
A link here would be useful for people who like to see a nicer summary of recent updates.

![Image](https://github.com/bonny/WordPress-Simple-History/assets/221570/a52ad09f-b1bc-408c-b4db-02dfd7eb0430)

Relevant filters:
```
/**  
		 * Filters the list of action links available following bulk plugin updates.  
		 * @since 3.0.0  
		 * @param string[] $update_actions Array of plugin action links.  
		 * @param array    $plugin_info Array of information for the last-updated plugin.  
		 */  
		$update_actions = apply_filters( 'update_bulk_plugins_complete_actions', $update_actions, $this->plugin_info );

---

$update_actions = apply_filters( 'update_bulk_theme_complete_actions', $update_actions, $this->theme_info );

---

$update_actions = apply_filters( 'update_translations_complete_actions', $update_actions );

```

**Comment by bonny** [comment]
Result

![Image](https://github.com/bonny/WordPress-Simple-History/assets/221570/371145f2-5d45-4344-89e2-cee8303bb50f)

**Comment by CURA-Digital** [comment]
Any chance we can make this optional? All day long I've been accidentally clicking on it when blindly going to click the "Go to WordPress Updates" link expecting it to be the last link.

**Comment by bonny** [comment]
> Any chance we can make this optional? All day long I've been accidentally clicking on it when blindly going to click the "Go to WordPress Updates" link expecting it to be the last link.

@CURA-Digital I've added a filter `simple_history/show_action_link` that can be used to hide the link. In the most simple way this will remove the link for all users:

`add_filter("simple_history/show_action_link", "__return_false");`

This will be included in the next version of the plugin.
