### ISSUE TITLE
Simple Fix for Simple History: Save Settings

### ISSUE THREAD

**Issue by dec-mail** [bonny/WordPress-Simple-History#454]
I only found this PI a few weeks ago, and find it very useful!

ATM the only thing that is bugging me is that it does not save/keep the selected options, but constantly resets them back to defaults
Which is annoying.

**Comment by bonny** [comment]
@dec-mail Can you provide some more info about your setup and the bug you're having? Like what's your WP version, db version, any other plugins installed?

I can save the settings fine on my sites, so it sounds like there is some conflict/bug that only happens on your setup.

**Comment by bonny** [comment]
No response so closing.
