### ISSUE TITLE
example for custom log with hyperlink

### ISSUE THREAD

**Issue by 1ucay** [bonny/WordPress-Simple-History#459]
Hi, how can I add a message with custom html? I saw some interpolate function, but it is possible allow custom html?

    apply_filters( 'simple_history_log', sprintf( __( 'User <a href="%s">{user_email}</a> ( %s )', 'ccc' ), admin_url( 'user-edit.php?user_id=' . $customer->ID ), implode( ', ', $errors ) ),
        [
            'user_id'    => $customer->ID,
            'user_email' => $customer->user_email,
            'fields'     => array_keys( $errors )
        ],
        'alert'
    );

Thank you.

**Comment by bonny** [comment]
You can't add HTML directly to a logged message due to security reasons.

Please see these similar questions:

- https://wordpress.org/support/topic/include-hyperlink-in-custom-log-message/
- https://wordpress.org/support/topic/htlm-links-in-the-message/
