### ISSUE TITLE
Classes in the plugin's folder

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#46]
WP scans the plugin's folder for `*.php`.
Plese consider moving classes to a subdir.

**Comment by szepeviktor** [comment]
And `examples.php`.

**Comment by bonny** [comment]
Thanks for the tips, will fix that.

**Comment by szepeviktor** [comment]
Please do not forget about ` SimpleHistoryLogQuery.php` and ` SimpleHistory.php`.

> WP scans the plugin's folder for *.php.
> Plese consider moving classes to a subdir.

**Comment by szepeviktor** [comment]
I think `/inc` is usually the class' dir.

**Comment by szepeviktor** [comment]
Please correct the link in the README:
https://github.com/bonny/WordPress-Simple-History/blob/master/examples.php

**Comment by szepeviktor** [comment]
John did it https://github.com/bonny/WordPress-Simple-History/commit/465d742ebf1e534f7a23e9fd2af66747abe469c6#diff-04c6e90faac2675aa89e2176d2eec7d8
