### ISSUE TITLE
"Containing words" isn't transable.

### ISSUE THREAD

**Issue by NekoJonez** [bonny/WordPress-Simple-History#470]
![image](https://github.com/user-attachments/assets/789e0e28-fba7-4256-bdd7-8c0b2aaf38d5)

I have translated Simple History 100% for my locale, yet "Containing words" doesn't appear to be able to be translated in my websites. :(

**Comment by bonny** [comment]
Thanks for reporting this. It's probably something I missed when I rewrote the GUI in React. Will take a look at it!
