### ISSUE TITLE
Add Quick View as experimental feature

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#476]
The _Quick View_ feature adds the 5 last entries to the log in the admin bar.

This makes it easy to quickly see what's happening on the site, without the need to switch to the history feed page in a new tab or moving to a new page and then going back again.

A great way to keep track what other admins or users on a website is doing. Or just to remember what you did yourself :).

For performance reasons the log is not loaded (using the REST API) until user mouse overs or clicks the history in the admin bar.

Name suggestions:

- Quick Peek
- History Quick Peek
- Quick History Peek
- Quick History
- Quick History View
- Activity Peek
- Quick Activity View
- Quick View

## Features

- [x] Add admin bar item
- [x] Load events on hover or click
- [x] Reload button if already loaded

## Maybe future features

- [ ] Checkbox "Auto reload in background" and add notification dot when new events are available

## Inspiration

This kind of feed exists at many places. Examples:

WordPress 6.3 added this I believe:
![Image](https://github.com/user-attachments/assets/56483b63-c017-4330-bc82-68613d6e0b41)

Also this:
![Image](https://github.com/user-attachments/assets/02009748-9637-4dd8-b65d-c9c751672761)

GitHub has a nice one too:
![Image](https://github.com/user-attachments/assets/5855adce-3327-423e-a07c-d471b2d6b6f8)

![Image](https://github.com/user-attachments/assets/43ca58a3-2a04-491d-98ed-b414b4b50c94)

![Image](https://github.com/user-attachments/assets/8d3b1f18-f329-4b5d-95db-2b743d0549bd)

![Image](https://github.com/user-attachments/assets/e7c21bc4-ea2b-48b3-bc2a-596629850dec)

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bonny** [comment]
Progress:

![Image](https://github.com/user-attachments/assets/c8cbecb1-3bc5-4519-8bff-9b6e7449f8bb)

**Comment by bonny** [comment]
Pretty close. Very useful now!

![Image](https://github.com/user-attachments/assets/1e93de50-5241-4f63-b79d-f7eb8e286619)
