### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#49]
Please avoid globals

```php
$GLOBALS["simple_history"] = new SimpleHistory();
```

and constantly changing contants in a class.

```php
const VERSION = "2.0.21";
```

The plugin's main file is for storing the version.

**Comment by szepeviktor** [comment]
https://github.com/bonny/WordPress-Simple-History/blob/master/SimpleHistoryFunctions.php could me merged into the main plugin file. It is so little.

**Comment by szepeviktor** [comment]
If you need a class somewhere else you can store its instance in a static property.

**Comment by szepeviktor** [comment]
http://stackoverflow.com/a/9159235/1606933

**Comment by szepeviktor** [comment]
And all those `require()`-s could be turned into: http://php.net/manual/en/language.oop5.autoload.php

**Comment by bonny** [comment]
thanks for the feedback. use singleton now.

**Comment by szepeviktor** [comment]
Do you plan to move `const VERSION` into the main plugin file?

**Comment by szepeviktor** [comment]
I tell you that I'd like to make this plugin and actually use it in production.
There should be *only* two thing OK:

- security
- speed (PHP and also MySQL)

Do you have plans for any of those?

**Comment by bonny** [comment]
Not sure I understand the gain of having a constant called for example `SIMPLE_HISTORY_VERSION` vs having the constant `VERSION` directly in the main class. Can you explain?

**Comment by szepeviktor** [comment]
When you release you don't have to fiddle with a class, only the main file.
Providing in the near future you decide to develop an automated release/build process.

**Comment by szepeviktor** [comment]
A *class* means some kind of abstraction for me.

**Comment by szepeviktor** [comment]
Put everything in its place:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#23-side-effects

**Comment by szepeviktor** [comment]
:smile: Do not click the above link, they have a version number as a `const`!
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#41-constants

**Comment by szepeviktor** [comment]
At least that is a *class* version, not a product version.

**Comment by bonny** [comment]
Actually it makes sense to only have to change the version number in the main file. Good point! A couple of times I did miss to change the version number because I had to change at many places ;)

**Comment by szepeviktor** [comment]
I develop automated scripts this way:

1. pseudo script based on manual routine (for copy&pasting)
1. corrections when copy&pasting
1. when there is no need for changes, add error checking
1. try the fully automated in a test environment

**Comment by szepeviktor** [comment]
I think in 2 or 3 releases you can put together a relase script.

**Comment by szepeviktor** [comment]
This is in the stage of a *pseudo script*:
https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup.sh

**Comment by szepeviktor** [comment]
When you see your manual step in one file you are closer to getting *the picture*.
