### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#50]
You can add a small script to the plugin build process that *optimizes out* code like this

```php
if ( defined("SIMPLE_HISTORY_LOG_DEBUG") && SIMPLE_HISTORY_LOG_DEBUG ) {
```

These shouldn't get into releases.
So a build process separates source code from the released software package.

Anyone wishing to debug could directed here to this repo.

**Comment by bonny** [comment]
Thanks but I'll like to keep that since I use it on some installations.

**Comment by szepeviktor** [comment]
Try

```php
define( 'WHATS_RUNNING_HIGHLIGHT', 'wp-content/plugins/simple-history' );
```
