### ISSUE TITLE
Hook to display UI for only one user

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#52]
Do you have a hook to display Simple History UI for only an `array` of userID-s?

**Comment by szepeviktor** [comment]
I'd like to hide the history from everyone.

**Comment by bonny** [comment]
Good idea, I'll add a hook for that.

**Comment by szepeviktor** [comment]
`simple_history/logger/load_logger` and `simple_history/dropin/load_dropin` are not for this purpose.
Am I right?

**Comment by bonny** [comment]
Nope, that's for other things. Haven't had the time to look at this issue more yet.

**Comment by szepeviktor** [comment]
OK. Thank you!

**Comment by szepeviktor** [comment]
Thank you.
