### ISSUE TITLE
How to find a directory

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#54]
```php
__DIR__ . "/../
```

Please be advised how to do this:
https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo.php#L36-L38
https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo-main.php#L13-L29

**Comment by szepeviktor** [comment]
And actually `__DIR__ . "/../` should be `dirname( dirname( __FILE__ ) )`.

**Comment by bonny** [comment]
will be fixed in 2.0.23

**Comment by szepeviktor** [comment]
Thanks.
Should I keep commenting?
