### ISSUE TITLE
Admin-frontend separation

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#55]
Is it a good idea to separate code for admin pages and the frontend?

Maybe you could benefit from it:

- more managable code
- faster execution

**Comment by szepeviktor** [comment]
I know it takes a lot of effort to clear the admin+frontend mixture.

**Comment by bonny** [comment]
the way it works with loggers and dropins, it will be difficult to separate. each dropin or logger takes care of it's own thing...

**Comment by szepeviktor** [comment]
Here you could say something like:
```php
if(!is_admin()) $loggersFiles = glob( $loggersDir . '*_frontend.php' );
```
https://github.com/bonny/WordPress-Simple-History/blob/master/inc/SimpleHistory.php#L580

Be aware of WP [entry points](https://github.com/szepeviktor/WPHW/blob/master/wp-entry-points.md)!

**Comment by szepeviktor** [comment]
...But there could be strange operations on the frontend like theme operations. You could add a filter to always execute every logger - like now.
