### ISSUE TITLE
Code design

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#56]
https://github.com/bonny/WordPress-Simple-History/blob/master/templates/settings-statsLoggers.php
Please consider functional separation.

- a function to query the DB (`$wpdb->prepare()`)
- a function to calculate values into one object
- a function to ouput the template
- a function to include CSS, JS

You must know MVC.

**Comment by bonny** [comment]
that function/feature is still work in progress and only available to devs so far
