### ISSUE TITLE
MySQL optimization

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#57]
If you are querying the DB by other fields than `id` there should be indexes for those queries.
https://github.com/bonny/WordPress-Simple-History/blob/master/inc/SimpleHistory.php#L1003

A simple way to debug it is to turn on
http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_log_queries_not_using_indexes
on your dev box.

**Comment by szepeviktor** [comment]
What is `$first_install` for in inc/SimpleHistory.php?

**Comment by bonny** [comment]
Thanks, I've started to log queries now. Let's see what shows up.

The `$first_install` is not used right now, but may be in the future.

**Comment by szepeviktor** [comment]
Use `mysqldumpslow` on the query log.
