### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#60]
Please consider using WP's Thickbox (when clicking on the date)
as in https://github.com/szepeviktor/option-inspector *this plugin shows the values of serialized wp-options*.

**Comment by bonny** [comment]
nah, i'm happy with my own. but let me know if something isn't working with it.

**Comment by szepeviktor** [comment]
There are two lightboxes in the plugin, Thickbox and your own.
Maybe one is enough.
