### ISSUE TITLE
Non-WP.org plugin's "View plugin info"

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#61]
Please handle non-WP.org plugins.

**Comment by bonny** [comment]
Please be more specific. What does/does not work currently?

**Comment by szepeviktor** [comment]
Try installing a non-WP.org plugin and open its log item.

**Comment by bonny** [comment]
can you try version 2.0.25 and see if it works for you?

**Comment by szepeviktor** [comment]
Actually the release has `Version 2.0.24` in it.

**Comment by szepeviktor** [comment]
The `View plugin info` still points to
```
/wp-admin/plugin-install.php?tab=plugin-information&plugin=github-link&section=&TB_iframe=true&width=640&height=550
```
Uploaded from [this ZIP](https://github.com/szepeviktor/github-link/archive/master.zip).

**Comment by szepeviktor** [comment]
Maybe a separate issue: when overwriting 2.0.24 with the GitHub release 2.0.25 (which is also 2.0.24 in it)
```
Updated plugin "Simple History" to 2.0.24 from {plugin_prev_version} 
```

**Comment by szepeviktor** [comment]
I don't know what to do with plugins not on WP.org. How to detect it and what info should be displayed.
Warning: Even an uploaded ZIP could contain a plugin on WP.org.

**Comment by szepeviktor** [comment]
But in `Installed plugin "GitHub Link" ` the `View plugin info` link displays GitHub's readme.

**Comment by szepeviktor** [comment]
Relative icons in my [readme](https://github.com/szepeviktor/github-link/blob/master/README.md) are not displayed. You could wrap it in an `<iframe>` or something...

**Comment by szepeviktor** [comment]
On plugin upload please mute these

- Deleted attachment "test-plugin2-master.zip" ("test-plugin2-master.zip") 
- Deleted media "test-plugin2-master.zip"

**Comment by szepeviktor** [comment]
At https://github.com/bonny/WordPress-Simple-History/blob/master/loggers/SimplePluginLogger.php#L206-L210 it could be
```php
$github_markdown_css = '
<long style>
'
```

**Comment by szepeviktor** [comment]
Or better read it from a `.css` file!

**Comment by szepeviktor** [comment]
Please be consistent with the quotes:
https://github.com/bonny/WordPress-Simple-History/blob/master/loggers/SimplePluginLogger.php#L157-L160

**Comment by szepeviktor** [comment]
Now you have several issues in one.

**Comment by bonny** [comment]
Too many mixed issues here now. Please open now issue for each problem you find.

**Comment by szepeviktor** [comment]
Done.
