### ISSUE TITLE
"Logged in" but who?

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#62]
Is it possible to add the `user_login` to this message?

**Comment by bonny** [comment]
In what context do you need it? In the GUI, the RSS-feed, other..?

**Comment by szepeviktor** [comment]
I suppose both the RSS feed and the GUI.
I think it is very important.

**Comment by bonny** [comment]
But is not the user name + email enough?

**Comment by szepeviktor** [comment]
It is up to you how to identify the logged in user.  Please do it at logout also.

**Comment by szepeviktor** [comment]
Now I only see "Logged in" and have to click once more to find you who has logged in.

**Comment by bonny** [comment]
Does your logged in entries not look like this:
http://i.glui.me/1MPYuWE
I.e. both email and user name visible?

**Comment by szepeviktor** [comment]
![no name](http://i.snag.gy/heXWA.jpg)

**Comment by szepeviktor** [comment]
Oh! I am very sorry.
i've just realized `You` is displayed.

**Comment by bonny** [comment]
no worries, glad we solved it :)

**Comment by szepeviktor** [comment]
Can `"simple_history/header_initiator_html_existing_user"` be filtered to restore the original `$tmpl_initiator_html`?

**Comment by szepeviktor** [comment]
You could include it as an example: `simple-history-not-me.php`

```php
<?php
/*
Plugin Name: Not me! for Simple History
*/

add_filter( 'simple_history/header_initiator_html_existing_user', 'simple_history_not_me' );
function simple_history_not_me( $tmpl ) {
    $tmpl = '
        <strong class="SimpleHistoryLogitem__inlineDivided">%3$s</strong>
        <span class="SimpleHistoryLogitem__inlineDivided SimpleHistoryLogitem__headerEmail">%2$s</span>
        ';
    return $tmpl;
}
```

**Comment by szepeviktor** [comment]
For those who can't read `You`.
