### ISSUE TITLE
404 logger

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#63]
Could you write a howto, or at least 4 sentences on adding a logger.
Maybe others would contribute loggers.

**Comment by szepeviktor** [comment]
Is this it implemented?
https://github.com/bonny/WordPress-Simple-History/blob/master/examples/example-logger.php#L72
Themes may lack 404 template.
I use `add_action( 'template_redirect', ...` and `! is_404()`
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/wordpress-fail2ban/mu-plugin/wp-fail2ban-mu.php#L190

**Comment by szepeviktor** [comment]
Here it is: https://github.com/bonny/WordPress-Simple-History/blob/master/examples/example-logger.php

**Comment by bonny** [comment]
It's not very "official" yet, but I did make a plugin that extends Simple History to include some more loggers, including that 404-example one:
https://wordpress.org/plugins/developer-loggers-for-simple-history/

**Comment by szepeviktor** [comment]
Thank you.
