### ISSUE TITLE
GHU header

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#66]
Please add GHU header to your plugin.

**Comment by szepeviktor** [comment]
It is a **very** easy one.

**Comment by szepeviktor** [comment]
off: I see you're progressing with Simple-History development.

**Comment by bonny** [comment]
Not sure I see the benefit of this at the moment. I already release the plugin at wordpress.org and I don't want to have two methods when I release a new version.

**Comment by szepeviktor** [comment]
It makes it possible to update your plugin with [GHU](https://github.com/afragen/github-updater).
It **does not** interfere with anything.

**Comment by bonny** [comment]
ah, maybe I misread, I thought that I needed to tag the releases in different ways. Still worried that people will start sending bug reports because they update to a non-released version..

**Comment by bonny** [comment]
hm.. also this:

> If you develop your plugin on GitHub and it also resides in the WP.org repo, the plugin will preferentially pull updates from WP.org

wouldn't that make the header useless/same as just installing the plugin from wp.org?

**Comment by szepeviktor** [comment]
Please read this on versions: https://github.com/afragen/github-updater#versions

> wouldn't that make the header useless/same as just installing the plugin from wp.org?

If you don't have GHU plugin that header is really useless.

**Comment by bonny** [comment]
ah. ok, gotcha! sounds fair then
