### ISSUE TITLE
WordPress 3.8.x (in-)compatibility

### ISSUE THREAD

**Issue by rmpel** [bonny/WordPress-Simple-History#67]
According to your page on WordPress.org, this plugin is compatible with WP 3.6 and up, but on 8 individual WordPress 3.8.x sites the plugin does NOT work properly. The History page (WP-Admin > Dashboard > Simple History) stays blank
![simple-history-blank-screen](https://cloud.githubusercontent.com/assets/1086776/6913863/622236b6-d785-11e4-8658-a3ca7aa4cdcb.png)

In some cases the console.log reports something about about an invalid data pseudo selector (?? paraphrased). The javascript error occurs in jQuery, but upgrading jQuery to 1.11 or even a 2.0 version does not help.
I've searched the plugin for :data in order to find and debug the problem with no success.

I've tried with 2.0.21, 2.0.22, 2.0.24 and 2.0.26. I hope you can tell me what to do about this, or at least point me in the right direction so I can (possibly) debug this for you.

**Comment by bonny** [comment]
Just created a new site here with WordPress 3.8 and tried Simple History on it. It seems to work with no problems (see screenshot). Any other plugin you have installed that may interfere with Simple History? Could you perhaps open the console before loading the page again and see if it outputs anything?

![image](https://cloud.githubusercontent.com/assets/221570/6935715/d1a1dbf8-d849-11e4-9a46-2068e68b16a6.png)

**Comment by rmpel** [comment]
Thanks for your response, I'm baffled! And shame on me for not testing with a vanilla WP38. The sites I tested on all have different themes/plugins, there's not one that is on all sites. (That's why I didn't look elsewhere, sorry)
I will keep trying, thank you for your nudge in the right direction :)

**Comment by rmpel** [comment]
Found it (I think...)
The problem as far as I can now determine is in
simple-history/dropins/SimpleHistorySidebarDropin.php
around line 130 
it says: if not english, then check for translations
(our sites are Dutch)
then it requires the file wp-admin/includes/translation-install.php which does not exist before version 4.0
the wp-admin page breaks on the require_once and when skipped by substituting include_once breaks on the function call wp_get_available_translations.
Footer is not printed, ergo scripts are not ran, ergo history table stays empty.

So, I'm sorry to say; simple-history is broken on all WordPress sites before 4.0 in a non-english language.

Hope this helps you solve the issue :)

**Comment by bonny** [comment]
thanks! great debugging. will fix it then :)

**Comment by bonny** [comment]
ok, brand new version only for you: https://wordpress.org/plugins/simple-history/changelog/
please let me know if it works!
