### ISSUE TITLE
Clean coding

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#71]
At https://github.com/bonny/WordPress-Simple-History/blob/master/loggers/SimplePluginLogger.php#L213-L217 it could be
```php
$github_markdown_css = '
<long style string broken at spaces>
';
```

**Comment by szepeviktor** [comment]
Or better: read it from a `.css` file! (WP Filesystem API)

**Comment by szepeviktor** [comment]
+1 Please be consistent with quotes and spaces:
https://github.com/bonny/WordPress-Simple-History/blob/master/loggers/SimplePluginLogger.php#L157-L160

**Comment by szepeviktor** [comment]
Please note the quotes.

**Comment by szepeviktor** [comment]
@bonny 
off: Have you seen Stream 3?
http://us3.campaign-archive1.com/?u=a3b52d421000c17c6a9d96652&id=519b428c6b

**Comment by bonny** [comment]
hm.. no screenshots? anyway, good that they move back to storing the history locally.
