### ISSUE TITLE
External logger for  PHP errors and WP deprication warnings

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#72]
Is SImple History pluggable?
Is it possible from another plugin to add loggers and dropins?

**Comment by szepeviktor** [comment]
It may be the `simple_history/loggers_to_instantiate` filter.
Could you add an action which is more appropriate for addig loggers?

**Comment by bonny** [comment]
Yep, it's pluggable already. external loggers exist, for example https://github.com/wp-plugins/ngg-simple-history.

I still have to decide a more easy way to load external loggers.

What does the subject of this issue mean? **PHP errors as log items**? It does not have anything to do whit the comments..?

**Comment by szepeviktor** [comment]
I'd like to write a PHP error logger.

**Comment by szepeviktor** [comment]
That may log WP's deprication warnings.

**Comment by szepeviktor** [comment]
Thank you for the example.
Please consider adding a very simple example here in this repo.
It could be an error logger. http://php.net/manual/en/function.set-error-handler.php

**Comment by bonny** [comment]
There is an example logger now:
https://github.com/bonny/WordPress-Simple-History/blob/master/examples/example-logger.php

I will also soon add a dropin example.

**Comment by szepeviktor** [comment]
Thank you.
What is the function of a dropin in this case?
