### ISSUE TITLE
"Undefined variable: id_or_email"- notice for ajax-response

### ISSUE THREAD

**Issue by tobiasnygren** [bonny/WordPress-Simple-History#74]
I get following notice if I have WP_DEBUG turned on (in Simple History v2.0.30):  

Undefined variable: id_or_email in wp-content/plugins/simple-history/inc/SimpleHistory.php on line 2465

**Comment by bonny** [comment]
thanks! will be fixed in next version.

**Comment by tobiasnygren** [comment]
\o/
