### ISSUE TITLE
No error message on sqlite backend

### ISSUE THREAD

**Issue by szepeviktor** [bonny/WordPress-Simple-History#76]
Simple History just does not work, no items in the history.
This is the backend:
https://wordpress.org/plugins/sqlite-integration/

Is it possible that you use a special MySQL query that is not sqlite compatible?

**Comment by bonny** [comment]
Yes, probably incompatible sql query. I'm using some pretty complex ones. Both MySQL and MariaDB should be fine.

**Comment by szepeviktor** [comment]
Is it possible that you do not check for error on SQL queries?

**Comment by szepeviktor** [comment]
https://github.com/bonny/WordPress-Simple-History/blob/40e63d519bbfe6d11c290a87a54543a9ae3890f2/templates/settings-statsLogLevels.php#L31

**Comment by szepeviktor** [comment]
Please consider error checking.
