### ISSUE TITLE
Login error when email address used for username

### ISSUE THREAD

**Issue by brigneld** [bonny/WordPress-Simple-History#77]
When I login to my wordpress site with an email address rather than a username, Simple History records a login error, even though the login is successful.
![simple_history_error](https://cloud.githubusercontent.com/assets/4124812/7905517/3c70ffb6-085d-11e5-87fd-c657c8806a46.png)

**Comment by bonny** [comment]
I guess you use a plugin to enable login by email? Can you say which one and I'll take a look at it.

**Comment by brigneld** [comment]
Yes, the plugin is WP Email Login. I've just started using it, and all
the existing users have previously used usernames only. It's possible,
although I haven't checked, that WP is treating all users as unverified
- but it still allows them to login.



On Mon, Jun 1, 2015, at 06:42 PM, Pär Thernström wrote:
> I guess you use a plugin to enable login by email? Can you say which
> one and I'll take a look at it.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/bonny/WordPress-Simple-History/issues/77#issuecomment-107367764

**Comment by afillbrandt** [comment]
the problem: in `authenticate` from WordPress "$username" could be the login or the email. So line 754 in loggers/SimpleUserLogger.php will fail

    // If username is not a user in the system then this
    // is consideraded a failed login attempt
    $wp_user = get_user_by("login", $username);

quick fix:

    // If username is not a user in the system then this
    // is consideraded a failed login attempt
    $check_string = ( is_email( $username ) ) ? 'email' : 'login';
    $wp_user = get_user_by( $check_string, $username );

- Alex
