### ISSUE TITLE
make it multisite compatible

### ISSUE THREAD

**Issue by nicmare** [bonny/WordPress-Simple-History#79]
please make it multisite compatible. you can not activate it from one place in network plugin page. you have to do it on each single network site which is not very comfortable. and would be nice to have one instance of simple history in network settings page where all changes are recorded and gathered in one place. so every change of every site is shown here.

**Comment by bonny** [comment]
It works for me when I activate it network wide. Can you give more details?

**Comment by nicmare** [comment]
strange. you are right. i tried it again now (Version 2.1.3). hmm – is this new? anyway… thank yoU! ;)
