### ISSUE TITLE
add log for woocommerce product

### ISSUE THREAD

**Issue by sireneweb** [bonny/WordPress-Simple-History#81]
Hi,
could you add log for custom post type as woocommerce product and woocommerce categories ?

**Comment by bonny** [comment]
It is something I am considering. Could you give some examples of what kind of events and actions from WooCommerce you would like to see added?

**Comment by sireneweb** [comment]
For exemple : 
- Log added/modified/delete product
- Log added/modified/deleted categories products

We use different custom post type with wp-types, and we can see only post and page from native wordpress fonction
