### ISSUE TITLE
Please add time zone to the time stamp display

### ISSUE THREAD

**Issue by dlipper2** [bonny/WordPress-Simple-History#84]
We have lots of people working on a site in different timezones. Could you please change the timestamp display to include time zone notation?

**Comment by bonny** [comment]
thanks for the feedback. can you give an example of what kind of output you would like to see, and when. Always? Sometimes? Only for people in specific timezones.

**Comment by dlipper2** [comment]
Always when any time is given. (Not 18 minutes ago.) If it is always GMT
instead of the local blog time zone, just add that notation and you're
done. If the time varies, then always do in GMT or local blog zone, not a
mix.


On Saturday, September 5, 2015, Pär Thernström <notifications@github.com>
wrote:

> thanks for the feedback. can you give an example of what kind of output
> you would like to see, and when. Always? Sometimes? Only for people in
> specific timezones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bonny/WordPress-Simple-History/issues/84#issuecomment-137943279>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ajoah** [comment]
I confirm and the GMT date appears when you hover an "ago time" too.
Maybe you can replace this line : 
https://github.com/bonny/WordPress-Simple-History/blob/7fd1b4093cf3b1f19c03cc4b214ce485748a038f/loggers/SimpleLogger.php#L352

by 

`$date_datetime = new DateTime( get_date_from_gmt($row->date) );`

to use the Wordpress Timezone

**Comment by ajoah** [comment]
Perfect, thank you :)
