### ISSUE TITLE
Switch back event in User Switching isn't logged

### ISSUE THREAD

**Issue by johnbillion** [bonny/WordPress-Simple-History#89]
If you use the User Switching plugin to switch off and then switch back again, Simple History doesn't log the switch back event.

The reason for this is [this piece of logic](https://github.com/bonny/WordPress-Simple-History/blob/master/loggers/PluginUserSwitchingLogger.php#L75-L77) which means the event isn't logged unless the `$user_id` and `$old_user_id` parameters both correspond to a user.

When you switch back after being logged off [the `$old_user_id` parameter is boolean false](https://github.com/johnbillion/user-switching/blob/1.0.8/user-switching.php#L904-L905) because there is no old user.

**Comment by johnbillion** [comment]
In the Stream plugin, [this action is logged against the user switching back on](https://github.com/xwp/stream/blob/3.0.1/connectors/class-connector-user-switching.php#L179-L183), which makes the most sense.

**Comment by bonny** [comment]
Thanks!
