### ISSUE TITLE
Filter for user role

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#9]
Option/filter to filter the history for specific user roles. Too much info for the common user sometimes.

**Comment by ajoah** [comment]
Hi @bonny,

Do you have some examples to use this great feature  :heart_eyes: ? I have been searching for an hour but I can not find anything :tired_face:

**Comment by bonny** [comment]
Ah yes, I added an example to the example file now:
https://github.com/bonny/WordPress-Simple-History/blob/master/examples/examples.php

Also pasting it here:

```php
// Modify who can read a logger
// Modify the if part to give users access or no access to a logger
add_filter( 'simple_history/loggers_user_can_read/can_read_single_logger', function( $user_can_read_logger, $logger_instance, $user_id ) {
	// in this example user with id 3 gets access to the post logger
	// while user with id 8 does not get any access to it
	if ( $logger_instance->slug == "SimplePostLogger" && $user_id === 3 ) {
		$user_can_read_logger = true;
	} else if ( $logger_instance->slug == "SimplePostLogger" && $user_id === 9 ) {
		$user_can_read_logger = false;
	}
	return $user_can_read_logger;
}, 10, 3 );
```

Hope this is enough for you to get going!

**Comment by ajoah** [comment]
Thank you @bonny, it's perfect for my need for the moment.  :+1:

But is it possible to filter logs entries individually ? By `context_message_key` for example.

For example: 

- a user can view `post_updated` entries but not `post_deleted` entries (same logger)
- hide logs for a given post type for an user

**Comment by bonny** [comment]
Not very easily at the moment. The built in support is on a logger level. Could could perhaps do it by using some own custom SQL, but I'm afraid you have to figure that one out for yourself :/

**Comment by ajoah** [comment]
That is what I thought ^^'

Do you plan to add this possibility ?

**Comment by bonny** [comment]
It's not something that's on my roadmap at the moment.

**Comment by ajoah** [comment]
Ok, thank you for your answers and your great plugin 😃
