### ISSUE TITLE
RSS diabled by default and GUI

### ISSUE THREAD

**Issue by guillaumemolter** [bonny/WordPress-Simple-History#91]
This is related to #34 

I think since the RSS feed is a potential security issue, it should be disabled by default and enabled by users if they wish to use the feature, acknowledging that their weakening their security.

I'm already working on a PR in that spirit and it will respect the "simple UI" spirit of the plugin by hiding all RSS related settings when the feature is not enabled.

**Comment by bonny** [comment]
I agree that it may be a good idea to have it turned of by default for new installs. We do however need to think about the users that already have it installed, if they like and use the RSS feature they should not need to login to each installation and activate it.

**Comment by guillaumemolter** [comment]
Good call, I'll make sure to consider that.

**Comment by bonny** [comment]
Thanks, will be added in next release.
