### ISSUE TITLE
Causes "WordPress Failure Notice" when deleting themes

### ISSUE THREAD

**Issue by JustinTrouble** [bonny/WordPress-Simple-History#98]
I have a multisite installation made up of just two sites.
If I network activate Simple History, or activate it _only_ on the first site then *when trying to delete any theme* I get the infamous:
"WordPress Failure Notice
Are you sure you want to do this?
Please try again." error.

There is no error when deleting plugins, and it doesn't cause the error when activated _only_ on the second site.

**Comment by bonny** [comment]
sounds strange, but I'll see if I can reproduce it.

**Comment by bonny** [comment]
hm, in the title you say you get a failure when deleting themes, but in the body you talk about an error you get when you network activate the plugin. Which error is it? :)

**Comment by JustinTrouble** [comment]
There is no problem activating the Simple History plugin.
The error **only** occurs when trying to delete any theme.

I have updated my original report to clarify this (re-arranged the words) :o)

**Comment by bonny** [comment]
I did manage to reproduce this myself now, and it is fixed in the next version.
